In [1]:
#Урок 6 задание 2
#2) Измерены значения IQ выборки студентов,
#обучающихся в местных технических вузах:
#131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
#Известно, что в генеральной совокупности IQ распределен нормально.
#Найдите доверительный интервал для математического ожидания с надежностью 0.95.

import numpy as np

n = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

print (n)

[131 125 115 122 131 115 107  99 125 111]


In [2]:
# Найдем среднее арифметическое
l = len(n)
n_sa = n.sum()/l
n_sa

118.1

In [3]:
# Найдем среднее квадратичное отклонение
n2 = (n - n_sa)**2
n_sko = (n2.sum()/l)**0.5

print ('Среднее квадратичное отклонение =',n_sko)

Среднее квадратичное отклонение = 10.004498987955369


In [4]:
# Найдем смещенную и несмещенную оценки дисперсии
n_sod = n_sko*n_sko # или # n_nod = (n2.sum()/l)

n_nod = (n2.sum()/(l-1))

print ('Смещенная оценка дисперсии S^2=',n_sod)
print ('Несмещенная оценка дисперсии S^2=',n_nod)

Смещенная оценка дисперсии S^2= 100.09
Несмещенная оценка дисперсии S^2= 111.21111111111111


In [5]:
s0 = (n_nod)**0.5
s0 #среднее квадратичное отклонение по выборке (несмещенное)

10.54566788359614

In [6]:
c= 2.262 #обратное значение функции стандартного нормального распределения при Р=0.95 по таблице Стьюдента

t1 = n_sa + s0*c/((len(n))**0.5)

t2 = n_sa - s0*c/((len(n))**0.5)

print (f'Доверительный интервал находится в промежутке от {t2} до {t1}')

Доверительный интервал находится в промежутке от 110.55660776308164 до 125.64339223691834


In [9]:
#Задача 3
#Известно, что рост футболистов в сборной распределен нормально
#с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
#среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
#ожидания с надежностью 0.95.

D = 25
X = 174.2
n3 = 27
c = 1.96 # По Лапласу при P=0.95

In [10]:
s3 = (D)**0.5
s3 #среднее квадратичное отклонение по выборке

5.0

In [13]:
#H0 - вес пачки = 200 грамм, H0 - вес пачки != 200
t3_1 = X + c*s3/(n3**0.5)

t3_2 = X - c*s3/(n3**0.5)

print (f'Доверительный интервал находится в промежутке от {t3_2} до {t3_1}')

Доверительный интервал находится в промежутке от 172.31398912064722 до 176.08601087935276


In [14]:
#Задача 1
#Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
#zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
#ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
#Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
#Полученные значения должны быть равны.
#Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
#а затем с использованием функций из библиотек numpy и pandas.

zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])

ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [15]:
cov_hand =  np.mean(zp*ks) - np.mean(zp)*np.mean(ks)

cov_hand # Коваривация "вручную"

9157.839999999997

In [16]:
np.cov(zp,ks,ddof=0) # Ковариация с использованием функций nupmy

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [18]:
r = cov_hand/(np.std(zp)*np.std(ks))
r # Коэффициент корреляции Пирсона "вручную"

0.8874900920739158

In [20]:
np.corrcoef(zp,ks) # Коэффициент корреляции Пирсона с использованием функций numpy

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])